-- ═══════════════════════════════════════════════════════════════
-- V010__alter_users_bigint_id.sql
-- Convert erp_users.id UUID → BIGINT (11+ digit auto-increment)
-- + migrate data from sd_user + seed sd_user_role → erp_user_roles
-- ═══════════════════════════════════════════════════════════════
BEGIN;

-- ═══════════════════════════════════════════════════════════════
-- Step 1: legacy role mapping table (จาก sd_user_role)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.erp_user_roles (
    role_id      BIGINT PRIMARY KEY,       -- = sd_user_role.role_id (int8)
    title        VARCHAR(50) NOT NULL,
    lang         VARCHAR(10) NOT NULL DEFAULT 'en',
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.erp_user_roles (role_id, title) VALUES
    (1,  'Dev'),
    (2,  'Administrator'),
    (3,  'Company'),
    (4,  'Staff'),
    (5,  'Helpdask'),
    (6,  'Customer'),
    (7,  'Donate'),
    (8,  'Edittor'),
    (9,  'User'),
    (10, 'gaust')
ON CONFLICT (role_id) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════
-- Step 2: create new erp_users with BIGINT id
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.erp_users_new (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY
                                       (START WITH 10000000000 INCREMENT BY 1)
                                       PRIMARY KEY,
    created_at                     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at                     DATE,
    is_active                      BOOLEAN NOT NULL DEFAULT TRUE,

    -- legacy role_id (int8) from sd_user.role_id
    role_id                        BIGINT NOT NULL DEFAULT 9,
    -- app-level Role enum string
    role                           VARCHAR(20) NOT NULL DEFAULT 'user',

    -- ─── Identity (SQL: sd_user) ─────────────────
    first_name                     VARCHAR(100),                 -- SQL: NULLABLE
    last_name                      VARCHAR(100),                 -- SQL: NULLABLE
    preferred_name                 VARCHAR(100),
    full_name                      VARCHAR(200),
    nickname                       VARCHAR(100),
    username                       VARCHAR(150) NOT NULL UNIQUE,  -- SQL: NOT NULL
    email                          VARCHAR(255) NOT NULL UNIQUE,
    phone                          VARCHAR(18),                  -- SQL: phone_number
    mobile_number                  VARCHAR(18),
    line_id                        VARCHAR(100),                 -- SQL: lineid
    id_card                        VARCHAR(20),                  -- SQL: idcard

    -- ─── Profile ──────────────────────────────────
    gender                         VARCHAR(20),
    birthdate                      DATE,                         -- SQL: birthday
    avatar                         TEXT,
    avatar_path                    TEXT,                         -- SQL: avatarpath
    message                        TEXT,
    remark                         TEXT,

    -- ─── Auth ─────────────────────────────────────
    hashed_password                VARCHAR(255) NOT NULL,        -- SQL: password
    temporary_password             VARCHAR(255),                 -- SQL: password_temp

    -- ─── Status ───────────────────────────────────
    status                         SMALLINT NOT NULL DEFAULT 1,
    online_status                  VARCHAR(10) NOT NULL DEFAULT '0',
    active_status                  SMALLINT,                     -- legacy int2

    -- ─── Legacy grouping ──────────────────────────
    network_id                     BIGINT DEFAULT 1,
    network_type_id                BIGINT DEFAULT 0,
    type_id                        BIGINT DEFAULT 0,
    system_id                      VARCHAR(50) DEFAULT '1',
    location_id                    VARCHAR(50) DEFAULT '1',

    -- ─── Security ─────────────────────────────────
    is_verified                    BOOLEAN NOT NULL DEFAULT FALSE,  -- SQL: verified
    is_superuser                   BOOLEAN NOT NULL DEFAULT FALSE,
    verification_code              VARCHAR(64),
    password_reset_token           VARCHAR(64),
    password_reset_at              TIMESTAMPTZ,
    login_failed_count             SMALLINT NOT NULL DEFAULT 0,   -- SQL: loginfailed
    last_sign_in_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),  -- SQL: lastsignindate

    -- ─── Preferences (SQL: *_notification int2) ──
    public_notification            SMALLINT NOT NULL DEFAULT 0,
    sms_notification               SMALLINT NOT NULL DEFAULT 0,
    email_notification             SMALLINT NOT NULL DEFAULT 0,
    line_notification              SMALLINT NOT NULL DEFAULT 0,
    public_status                  SMALLINT NOT NULL DEFAULT 0,
    information_agreement_status   SMALLINT NOT NULL DEFAULT 0,  -- SQL: infomation_agree_status

    CONSTRAINT ck_users_new_status CHECK (status IN (0,1,2,9))
);

-- ═══════════════════════════════════════════════════════════════
-- Step 3: migrate data from sd_user
-- ═══════════════════════════════════════════════════════════════
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_schema='public' AND table_name='sd_user') THEN

        INSERT INTO public.erp_users_new (
            created_at, updated_at, deleted_at, is_active,
            role_id, role,
            first_name, last_name, preferred_name, full_name, nickname,
            username, email, phone, mobile_number, line_id, id_card,
            gender, birthdate, avatar, avatar_path, message, remark,
            hashed_password, temporary_password,
            status, online_status, active_status,
            network_id, network_type_id, type_id, system_id, location_id,
            is_verified, is_superuser, verification_code,
            password_reset_token, password_reset_at,
            login_failed_count, last_sign_in_at,
            public_notification, sms_notification,
            email_notification, line_notification,
            public_status, information_agreement_status
        )
        SELECT
            u.createddate,
            u.updateddate,
            u.deletedate,
            CASE
                WHEN u.active_status IS NULL THEN
                    CASE WHEN u.status = 1 THEN TRUE ELSE FALSE END
                ELSE (u.active_status = 1)
            END,
            COALESCE(u.role_id, 9),
            CASE u.role_id
                WHEN 1 THEN 'admin'
                WHEN 2 THEN 'admin'
                WHEN 10 THEN 'guest'
                ELSE 'user'
            END,
            NULLIF(u.firstname, ''),
            NULLIF(u.lastname, ''),
            COALESCE(NULLIF(u.nickname, ''), NULLIF(u.firstname, '')),
            NULLIF(u.fullname, ''),
            NULLIF(u.nickname, ''),
            u.username,
            u.email,
            NULLIF(NULLIF(u.phone_number, '0'), ''),
            NULLIF(NULLIF(u.mobile_number, '0'), ''),
            NULLIF(NULLIF(u.lineid, '0'), ''),
            NULLIF(u.idcard, ''),
            NULLIF(u.gender, ''),
            u.birthday,
            NULLIF(u.avatar, ''),
            NULLIF(u.avatarpath, ''),
            u.message,
            u.remark,
            u.password,
            u.password_temp,
            COALESCE(u.status, 1),
            COALESCE(NULLIF(u.online_status, ''), '0'),
            u.active_status,
            COALESCE(u.network_id, 1),
            COALESCE(u.network_type_id, 0),
            COALESCE(u.type_id, 0),
            COALESCE(u.system_id, '1'),
            COALESCE(u.location_id, '1'),
            COALESCE(u.verified, FALSE),
            COALESCE(u.is_superuser, FALSE),
            u.verification_code,
            u.password_reset_token,
            u.password_reset_at,
            COALESCE(u.loginfailed, 0),
            u.lastsignindate,
            COALESCE(u.public_notification, 0),
            COALESCE(u.sms_notification, 0),
            COALESCE(u.email_notification, 0),
            COALESCE(u.line_notification, 0),
            COALESCE(u.public_status, 0),
            COALESCE(u.infomation_agree_status, 0)
        FROM public.sd_user u
        WHERE u.email IS NOT NULL AND u.username IS NOT NULL
        ON CONFLICT (email) DO NOTHING;
    END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════
-- Step 4: swap tables
-- ═══════════════════════════════════════════════════════════════
DROP TABLE IF EXISTS public.erp_users CASCADE;
ALTER TABLE public.erp_users_new RENAME TO erp_users;

-- ═══════════════════════════════════════════════════════════════
-- Step 5: indexes
-- ═══════════════════════════════════════════════════════════════
CREATE INDEX IF NOT EXISTS ix_users_email_is_active
    ON public.erp_users (email, is_active);
CREATE INDEX IF NOT EXISTS ix_users_username
    ON public.erp_users (username);
CREATE INDEX IF NOT EXISTS ix_users_status
    ON public.erp_users (status);
CREATE INDEX IF NOT EXISTS ix_users_role
    ON public.erp_users (role);
CREATE INDEX IF NOT EXISTS ix_users_created_at
    ON public.erp_users (created_at DESC);

-- ═══════════════════════════════════════════════════════════════
-- Step 6: updated_at trigger
-- ═══════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.set_updated_at_users()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated ON public.erp_users;
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON public.erp_users
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_users();

COMMIT;
