"""YOLO application ports"""
from __future__ import annotations
import uuid
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, AsyncIterator, Protocol


class RequestContext(Protocol):
    @property
    def tenant_id(self) -> uuid.UUID: ...
    @property
    def user_id(self) -> uuid.UUID | None: ...


class DatasetRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, ds: Any) -> Any: ...
    @abstractmethod
    async def find_by_id(self, ctx: Any, id: uuid.UUID) -> Any | None: ...
    @abstractmethod
    async def find_by_name(self, ctx: Any, name: str) -> Any | None: ...
    @abstractmethod
    async def find_paginated(self, ctx: Any, page: int, size: int) -> tuple[list[Any], int]: ...
    @abstractmethod
    async def update(self, ctx: Any, ds: Any) -> Any: ...
    @abstractmethod
    async def soft_delete(self, ctx: Any, id: uuid.UUID) -> bool: ...


class ClassRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, cls: Any) -> Any: ...
    @abstractmethod
    async def find_by_id(self, ctx: Any, id: uuid.UUID) -> Any | None: ...
    @abstractmethod
    async def find_by_dataset(self, ctx: Any, dataset_id: uuid.UUID) -> list[Any]: ...
    @abstractmethod
    async def bulk_create(self, ctx: Any, classes: list[Any]) -> list[Any]: ...


class ImageRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, img: Any) -> Any: ...
    @abstractmethod
    async def find_by_id(self, ctx: Any, id: uuid.UUID) -> Any | None: ...
    @abstractmethod
    async def find_by_hash(self, ctx: Any, content_hash: str) -> Any | None: ...
    @abstractmethod
    async def find_by_dataset(self, ctx: Any, dataset_id: uuid.UUID,
                                split: str | None, page: int, size: int) -> tuple[list[Any], int]: ...
    @abstractmethod
    async def count_by_dataset(self, ctx: Any, dataset_id: uuid.UUID,
                                split: str | None) -> int: ...


class AnnotationRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, ann: Any) -> Any: ...
    @abstractmethod
    async def bulk_create(self, ctx: Any, annotations: list[Any]) -> list[Any]: ...
    @abstractmethod
    async def find_by_id(self, ctx: Any, id: uuid.UUID) -> Any | None: ...
    @abstractmethod
    async def find_by_image(self, ctx: Any, image_id: uuid.UUID) -> list[Any]: ...
    @abstractmethod
    async def delete_by_image(self, ctx: Any, image_id: uuid.UUID) -> int: ...
    @abstractmethod
    async def class_distribution(self, ctx: Any, dataset_id: uuid.UUID) -> dict[str, int]: ...


class TrainingRepository(ABC):
    @abstractmethod
    async def create(self, ctx: Any, tr: Any) -> Any: ...
    @abstractmethod
    async def find_by_id(self, ctx: Any, id: uuid.UUID) -> Any | None: ...
    @abstractmethod
    async def find_by_dataset(self, ctx: Any, dataset_id: uuid.UUID) -> list[Any]: ...
    @abstractmethod
    async def update_status(self, ctx: Any, id: uuid.UUID, status: str) -> None: ...
    @abstractmethod
    async def set_best_model(self, ctx: Any, id: uuid.UUID, model_id: uuid.UUID) -> None: ...


class ModelRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, m: Any) -> Any: ...
    @abstractmethod
    async def find_by_id(self, ctx: Any, id: uuid.UUID) -> Any | None: ...
    @abstractmethod
    async def find_by_training(self, ctx: Any, training_id: uuid.UUID) -> list[Any]: ...
    @abstractmethod
    async def find_active(self, ctx: Any) -> list[Any]: ...
    @abstractmethod
    async def find_deployed(self, ctx: Any) -> list[Any]: ...
    @abstractmethod
    async def update(self, ctx: Any, m: Any) -> Any: ...


class InferenceRepository(ABC):
    @abstractmethod
    async def create(self, ctx: Any, inf: Any) -> Any: ...
    @abstractmethod
    async def find_by_model(self, ctx: Any, model_id: uuid.UUID, limit: int) -> list[Any]: ...
    @abstractmethod
    async def stats_by_model(self, ctx: Any, model_id: uuid.UUID,
                              since: datetime) -> dict[str, Any]: ...


class YOLOTrainer(Protocol):
    async def train(self, config: Any, aug_config: Any,
                     dataset_uri: str, classes: list[str]) -> dict[str, Any]: ...


class YOLODetector(Protocol):
    async def detect(self, model_id: uuid.UUID, image_bytes: bytes,
                      conf: float, iou: float) -> list[Any]: ...
    async def detect_batch(self, model_id: uuid.UUID, images: list[bytes],
                            conf: float, iou: float) -> list[list[Any]]: ...
    async def detect_stream(self, model_id: uuid.UUID, video_uri: str,
                             conf: float) -> AsyncIterator[list[Any]]: ...


class ModelRegistry(Protocol):
    async def load(self, model_id: uuid.UUID, weights_uri: str, format: str) -> None: ...
    async def unload(self, model_id: uuid.UUID) -> None: ...
    async def is_loaded(self, model_id: uuid.UUID) -> bool: ...


class ModelExporter(Protocol):
    async def export(self, model_id: uuid.UUID, weights_uri: str,
                      format: str, imgsz: int, opset: int) -> dict[str, Any]: ...


class Augmenter(Protocol):
    def build_pipeline(self, config: Any) -> Any: ...
    def augment(self, image: Any, bboxes: list[Any], class_ids: list[int],
                pipeline: Any) -> tuple[Any, list[Any], list[int]]: ...


class ArtifactStore(Protocol):
    async def save(self, path: str, data: bytes, metadata: dict[str, Any]) -> str: ...
    async def load(self, uri: str) -> bytes: ...
    async def exists(self, uri: str) -> bool: ...
    async def delete(self, uri: str) -> bool: ...


class Cache(ABC):
    @abstractmethod
    async def get(self, key: str) -> Any | None: ...
    @abstractmethod
    async def set(self, key: str, value: Any, ttl: int = 3600) -> bool: ...
    @abstractmethod
    async def invalidate(self, key: str) -> bool: ...


class EventBus(ABC):
    @abstractmethod
    async def publish(self, event: object) -> None: ...


class IdempotencyStore(ABC):
    @abstractmethod
    async def check_or_lock(self, key: str, scope: str,
                             payload: dict[str, Any]) -> dict[str, Any] | None: ...
    @abstractmethod
    async def complete(self, key: str, scope: str,
                        status: int, body: dict[str, Any]) -> None: ...


class RateLimiter(ABC):
    @abstractmethod
    async def check(self, tenant_id: uuid.UUID, user_id: uuid.UUID,
                     cost: int) -> bool: ...
    @abstractmethod
    async def increment(self, tenant_id: uuid.UUID, user_id: uuid.UUID,
                         cost: int) -> None: ...
