name: "fastapi-clean-ddd"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-clean-ddd
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: "5432"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      QUEUE_REDIS_URL: "redis://redis:6379/1"
      INFLUXDB_URL: "http://influxdb:8086"
      MQTT_BROKER: "mqtt://mosquitto:1883"
    expose:
      - "${APPLICATION_PORT}"
    networks:
      - fastapi-clean-ddd-network
    ports:
      - "${APPLICATION_PORT}:8000"
    restart: unless-stopped
    volumes:
      - ./:/app

  database:
    container_name: fastapi-clean-ddd-database
    environment:
      - "POSTGRES_DB=${POSTGRESQL_DATABASE}"
      - "POSTGRES_USER=${POSTGRESQL_USERNAME}"
      - "POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}"
    expose:
      - "${POSTGRESQL_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d \"$${POSTGRES_DB}\" -U \"$${POSTGRES_USER}\"" ]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
    image: "postgres:17.4-bullseye"
    networks:
      - fastapi-clean-ddd-network
    ports:
      - "${POSTGRESQL_PORT}:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:7-alpine"
    container_name: fastapi-clean-ddd-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
    expose:
      - "6379"
    networks:
      - fastapi-clean-ddd-network
    ports:
      - "6377:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  database-admin:
    image: "dpage/pgadmin4:9.2"
    container_name: fastapi-clean-ddd-database-admin
    depends_on:
      database:
        condition: service_healthy
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@localhost.com}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}"
    expose:
      - "${PGADMIN_PORT:-5050}"
    networks:
      - fastapi-clean-ddd-network
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  influxdb:
    image: "influxdb:2.7"
    container_name: fastapi-clean-ddd-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin12345678
      DOCKER_INFLUXDB_INIT_ORG: "${INFLUXDB_ORG}"
      DOCKER_INFLUXDB_INIT_BUCKET: "${INFLUXDB_BUCKET}"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${INFLUXDB_TOKEN}"
    expose:
      - "8086"
    networks:
      - fastapi-clean-ddd-network
    ports:
      - "9088:8086"
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb2

  mosquitto:
    image: "eclipse-mosquitto:2"
    container_name: fastapi-clean-ddd-mosquitto
    expose:
      - "1883"
      - "9001"
    networks:
      - fastapi-clean-ddd-network
    ports:
      - "1884:1883"
      - "9002:9001"
    restart: unless-stopped
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  postgres_data:
  pgadmin_data:
  influxdb_data:
  redis_data:
  mosquitto_data:
  mosquitto_log:

networks:
  fastapi-clean-ddd-network:
    name: fastapi-clean-ddd-network
