"""tenancy application interfaces — ports."""
from typing import Protocol

from ..domain.entities import Tenant


class ITenantRepository(Protocol):
    """Repository port."""

    async def save(self, tenant: Tenant) -> Tenant: ...
    async def get_by_id(self, id: str) -> Tenant | None: ...
    async def get_by_slug(self, slug: str) -> Tenant | None: ...
    async def list(self, page: int, limit: int) -> tuple[list[Tenant], int]: ...
    async def soft_delete(self, id: str) -> None: ...


class ITenantCache(Protocol):
    """Cache port."""

    async def get(self, id: str) -> Tenant | None: ...
    async def insert(self, id: str, tenant: Tenant) -> None: ...
    async def delete(self, id: str) -> None: ...


class ISchemaManager(Protocol):
    """Schema manager port."""

    async def create_schema(self, schema_name: str) -> None: ...
    async def drop_schema(self, schema_name: str) -> None: ...
    async def schema_exists(self, schema_name: str) -> bool: ...


__all__ = ["ITenantRepository", "ITenantCache", "ISchemaManager"]