"""
Revision Message: add_iot_tables

Revision ID: 04e00cccb1c5
Revises: a9a05a7f432d
Create Date: 2026-07-21 13:36:44.030361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04e00cccb1c5'
down_revision: Union[str, Sequence[str], None] = 'a9a05a7f432d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_activity_log',
    sa.Column('log_type', sa.String(length=50), nullable=False, comment='Log type'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity level'),
    sa.Column('data_json', sa.Text(), nullable=False, comment='Data JSON'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_alarm_log',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device ID'),
    sa.Column('alarm_action_id', sa.Integer(), nullable=False, comment='Alarm action ID'),
    sa.Column('alarm_type', sa.Integer(), nullable=False, comment='Alarm type'),
    sa.Column('alarm_status', sa.Integer(), nullable=False, comment='Alarm status'),
    sa.Column('value_data', sa.Float(), nullable=False, comment='Sensor value'),
    sa.Column('value_alarm', sa.Float(), nullable=False, comment='Alarm threshold'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Alarm title'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='Alarm subject'),
    sa.Column('content', sa.Text(), nullable=False, comment='Alarm content'),
    sa.Column('data_alarm', sa.Integer(), nullable=False, comment='Alarm data value'),
    sa.Column('data_alarm_raw', sa.Integer(), nullable=False, comment='Raw alarm data'),
    sa.Column('event_control', sa.Integer(), nullable=False, comment='Event control state'),
    sa.Column('message_mqtt_control', sa.String(length=500), nullable=False, comment='MQTT control message'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_data',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device ID'),
    sa.Column('data_json', sa.Text(), nullable=False, comment='Data payload JSON'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True, comment='Data timestamp'),
    sa.Column('location_id', sa.Integer(), nullable=False, comment='Location ID'),
    sa.Column('metadata_json', sa.Text(), nullable=False, comment='Metadata JSON'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_device',
    sa.Column('hardware_id', sa.Integer(), nullable=False, comment='Hardware identifier'),
    sa.Column('type_id', sa.Integer(), nullable=False, comment='Device type ID'),
    sa.Column('location_id', sa.Integer(), nullable=False, comment='Location ID'),
    sa.Column('device_sn', sa.String(length=100), nullable=False, comment='Serial number'),
    sa.Column('device_name', sa.String(length=255), nullable=False, comment='Device name'),
    sa.Column('device_type', sa.String(length=100), nullable=False, comment='Device type'),
    sa.Column('location_name', sa.String(length=255), nullable=False, comment='Location name'),
    sa.Column('mqtt_id', sa.Integer(), nullable=False, comment='MQTT config ID'),
    sa.Column('mqtt_main_id', sa.Integer(), nullable=False, comment='MQTT main broker ID'),
    sa.Column('mqtt_topic', sa.String(length=500), nullable=False, comment='MQTT topic'),
    sa.Column('mqtt_name', sa.String(length=255), nullable=False, comment='MQTT display name'),
    sa.Column('mqtt_username', sa.String(length=255), nullable=False, comment='MQTT username'),
    sa.Column('mqtt_password', sa.String(length=255), nullable=False, comment='MQTT password'),
    sa.Column('unit', sa.String(length=50), nullable=False, comment='Measurement unit'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Device status'),
    sa.Column('icon', sa.String(length=255), nullable=False, comment='Icon name'),
    sa.Column('icon_color', sa.String(length=50), nullable=False, comment='Icon color'),
    sa.Column('description', sa.String(length=500), nullable=False, comment='Description'),
    sa.Column('firmware_version', sa.String(length=50), nullable=False, comment='Firmware version'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_device_alert',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device ID'),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='Alert type'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity: low/medium/high/critical'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Alert title'),
    sa.Column('message', sa.String(length=1000), nullable=False, comment='Alert message'),
    sa.Column('value_data', sa.Float(), nullable=False, comment='Sensor value at alert'),
    sa.Column('value_alarm', sa.Float(), nullable=False, comment='Alarm threshold value'),
    sa.Column('resolved', sa.Boolean(), nullable=False, comment='Is resolved'),
    sa.Column('acknowledged', sa.Boolean(), nullable=False, comment='Is acknowledged'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_device_config',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device ID'),
    sa.Column('max_value', sa.Float(), nullable=False, comment='Maximum threshold'),
    sa.Column('min_value', sa.Float(), nullable=False, comment='Minimum threshold'),
    sa.Column('warning_threshold', sa.Float(), nullable=False, comment='Warning threshold'),
    sa.Column('alert_threshold', sa.Float(), nullable=False, comment='Alert threshold'),
    sa.Column('recovery_warning', sa.Float(), nullable=False, comment='Recovery warning level'),
    sa.Column('recovery_alert', sa.Float(), nullable=False, comment='Recovery alert level'),
    sa.Column('calibration_offset', sa.Float(), nullable=False, comment='Calibration offset'),
    sa.Column('calibration_multiplier', sa.Float(), nullable=False, comment='Calibration multiplier'),
    sa.Column('mqtt_control_on', sa.String(length=255), nullable=False, comment='MQTT control ON payload'),
    sa.Column('mqtt_control_off', sa.String(length=255), nullable=False, comment='MQTT control OFF payload'),
    sa.Column('action_name', sa.String(length=255), nullable=False, comment='Alarm action name'),
    sa.Column('config_json', sa.String(length=2000), nullable=False, comment='Additional config JSON'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_device_config_device_id')
    )
    op.create_table('iot_device_status',
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device ID'),
    sa.Column('is_online', sa.Boolean(), nullable=False, comment='Online status'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Last seen timestamp'),
    sa.Column('last_value', sa.Float(), nullable=False, comment='Last sensor value'),
    sa.Column('last_alarm', sa.Integer(), nullable=False, comment='Last alarm status'),
    sa.Column('count_alarm', sa.Integer(), nullable=False, comment='Alarm count'),
    sa.Column('event', sa.Integer(), nullable=False, comment='Event state'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status string'),
    sa.Column('sensor_data', sa.String(length=500), nullable=False, comment='Sensor data JSON'),
    sa.Column('sensor_min', sa.Float(), nullable=False, comment='Sensor min value'),
    sa.Column('sensor_max', sa.Float(), nullable=False, comment='Sensor max value'),
    sa.Column('sensor_avg', sa.Float(), nullable=False, comment='Sensor avg value'),
    sa.Column('battery', sa.Float(), nullable=False, comment='Battery level'),
    sa.Column('rssi', sa.Integer(), nullable=False, comment='Signal strength'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_device_status_device_id')
    )
    op.create_table('iot_schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False, comment='Schedule ID'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device ID'),
    sa.Column('start_time', sa.String(length=10), nullable=False, comment='Start time HH:MM'),
    sa.Column('end_time', sa.String(length=10), nullable=False, comment='End time HH:MM'),
    sa.Column('event', sa.String(length=50), nullable=False, comment='Event action'),
    sa.Column('monday', sa.Boolean(), nullable=False, comment='Monday'),
    sa.Column('tuesday', sa.Boolean(), nullable=False, comment='Tuesday'),
    sa.Column('wednesday', sa.Boolean(), nullable=False, comment='Wednesday'),
    sa.Column('thursday', sa.Boolean(), nullable=False, comment='Thursday'),
    sa.Column('friday', sa.Boolean(), nullable=False, comment='Friday'),
    sa.Column('saturday', sa.Boolean(), nullable=False, comment='Saturday'),
    sa.Column('sunday', sa.Boolean(), nullable=False, comment='Sunday'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iot_schedule')
    op.drop_table('iot_device_status')
    op.drop_table('iot_device_config')
    op.drop_table('iot_device_alert')
    op.drop_table('iot_device')
    op.drop_table('iot_data')
    op.drop_table('iot_alarm_log')
    op.drop_table('iot_activity_log')
    # ### end Alembic commands ###
