"""bigo application ports"""
from __future__ import annotations
import uuid
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Protocol

from app.modules.bigo.domain.value_objects import Complexity


class RequestContext(Protocol):
    @property
    def tenant_id(self) -> uuid.UUID: ...
    @property
    def user_id(self) -> uuid.UUID | None: ...


class MetricRepository(ABC):
    @abstractmethod
    async def create(self, ctx: Any, metric: Any) -> Any: ...
    @abstractmethod
    async def find_by_kind(self, ctx: Any, kind: str, since: datetime, limit: int) -> list[Any]: ...
    @abstractmethod
    async def aggregate(self, ctx: Any, name: str, since: datetime) -> dict[str, Any]: ...


class ProfileRepository(ABC):
    @abstractmethod
    async def create(self, ctx: Any, profile: Any) -> Any: ...
    @abstractmethod
    async def find_by_id(self, ctx: Any, id: uuid.UUID) -> Any | None: ...
    @abstractmethod
    async def find_by_function(self, ctx: Any, function_name: str, limit: int) -> list[Any]: ...
    @abstractmethod
    async def find_recent(self, ctx: Any, since: datetime, limit: int) -> list[Any]: ...


class MemoryRepository(ABC):
    @abstractmethod
    async def save_snapshot(self, ctx: Any, snap: Any) -> Any: ...
    @abstractmethod
    async def save_leak(self, ctx: Any, leak: Any) -> Any: ...
    @abstractmethod
    async def find_snapshots(self, ctx: Any, since: datetime, limit: int) -> list[Any]: ...
    @abstractmethod
    async def find_leaks(self, ctx: Any, status: str = "OPEN", limit: int = 50) -> list[Any]: ...
    @abstractmethod
    async def update_leak_status(self, ctx: Any, leak_id: uuid.UUID, status: str) -> bool: ...


class KafkaTopicRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, topic: Any) -> Any: ...
    @abstractmethod
    async def find_by_name(self, ctx: Any, name: str) -> Any | None: ...
    @abstractmethod
    async def find_all_active(self, ctx: Any) -> list[Any]: ...
    @abstractmethod
    async def update(self, ctx: Any, topic: Any) -> Any: ...


class KafkaQueueRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, q: Any) -> Any: ...
    @abstractmethod
    async def find_by_topic(self, ctx: Any, topic: str, limit: int) -> list[Any]: ...
    @abstractmethod
    async def latest_by_topic(self, ctx: Any, topic: str) -> list[Any]: ...
    @abstractmethod
    async def total_lag(self, ctx: Any, topic: str) -> int: ...


class KafkaConsumerRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, c: Any) -> Any: ...
    @abstractmethod
    async def find_by_group(self, ctx: Any, group_id: str) -> Any | None: ...
    @abstractmethod
    async def find_all(self, ctx: Any, limit: int) -> list[Any]: ...
    @abstractmethod
    async def update_lag(self, ctx: Any, consumer_id: uuid.UUID, total_lag: int, health: str) -> None: ...


class PipelineReportRepository(ABC):
    @abstractmethod
    async def save(self, ctx: Any, report: Any) -> Any: ...
    @abstractmethod
    async def find_recent(self, ctx: Any, since: datetime, limit: int) -> list[Any]: ...
    @abstractmethod
    async def find_by_trace(self, ctx: Any, trace_id: str) -> Any | None: ...


class ComplexityAnalyzer(Protocol):
    def analyze(self, fn: Any, sizes: list[int] | None = None) -> Complexity: ...


class MemoryProfiler(Protocol):
    def snapshot(self) -> list[tuple[str, int, int]]: ...
    def diff(self, before: list[tuple[str, int, int]], after: list[tuple[str, int, int]]) -> list[dict[str, Any]]: ...
    def info(self) -> dict[str, Any]: ...


class KafkaAdmin(Protocol):
    async def list_topics(self) -> list[str]: ...
    async def describe_topic(self, name: str) -> dict[str, Any]: ...
    async def consumer_lag(self, group_id: str, topic: str) -> dict[str, Any]: ...
    async def create_topic(self, name: str, partitions: int, replication: int) -> None: ...
    async def delete_topic(self, name: str) -> None: ...


class BackpressureController(Protocol):
    async def activate(self, topic: str, reason: str) -> None: ...
    async def deactivate(self, topic: str) -> None: ...
    async def is_active(self, topic: str) -> bool: ...


class CachePort(ABC):
    @abstractmethod
    async def get(self, key: str) -> Any | None: ...
    @abstractmethod
    async def set(self, key: str, value: Any, ttl: int = 60) -> bool: ...
    @abstractmethod
    async def invalidate(self, key: str) -> bool: ...


class EventBus(ABC):
    @abstractmethod
    async def publish(self, event: object) -> None: ...
