"""
Revision Message: initial schema

Revision ID: 7e826ae930fa
Revises:
Create Date: 2026-09-20 09:52:29.695702

"""

from collections.abc import Sequence

revision: str = "7e826ae930fa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
