"""
Revision Message: generate_initial_models

Revision ID: 93b93ee0f291
Revises:
Create Date: 2026-07-31 10:48:34.607109

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "93b93ee0f291"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fastapi_clean_architecture_ddd_template_users",
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=False,
            comment="First name of the user",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=False,
            comment="Last name of the user",
        ),
        sa.Column(
            "preferred_name",
            sa.String(length=100),
            nullable=False,
            comment="Preferred name of the user",
        ),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "NON_BINARY", "OTHER", name="gender_enum"),
            nullable=False,
            comment="Gender of the user",
        ),
        sa.Column(
            "birthdate", sa.Date(), nullable=False, comment="Birthdate of the user"
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Email address of the user",
        ),
        sa.Column(
            "phone",
            sa.String(length=18),
            nullable=True,
            comment="Phone number of the user",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            comment="Hashed password of the user",
        ),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MANAGER", "USER", name="role_enum"),
            nullable=False,
            comment="Role of the user",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the record",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Indicates whether the record is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        "ix_users_email_is_active",
        "fastapi_clean_architecture_ddd_template_users",
        ["email", "is_active"],
        unique=False,
    )
    op.create_table(
        "fastapi_clean_architecture_ddd_template_authentications",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the authentication",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Identifier of the user who owns the authentication",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=False,
            comment="IP address used when the authentication was created",
        ),
        sa.Column(
            "device",
            sa.String(length=255),
            nullable=False,
            comment="Human readable device name",
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=False,
            comment="User agent string of the client",
        ),
        sa.Column(
            "accept_language",
            sa.String(length=255),
            nullable=True,
            comment="Accept-Language header value of the client",
        ),
        sa.Column(
            "accept-encoding",
            sa.String(length=255),
            nullable=True,
            comment="Accept-Encoding header value of the client",
        ),
        sa.Column(
            "origin",
            sa.String(length=255),
            nullable=False,
            comment="Origin header value of the client",
        ),
        sa.Column(
            "referrer",
            sa.String(length=255),
            nullable=True,
            comment="Referrer header value of the client",
        ),
        sa.Column(
            "location",
            sa.String(length=255),
            nullable=True,
            comment="Approximate geographic location of the client",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the authentication was created",
        ),
        sa.Column(
            "last_update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Last time the authentication was updated",
        ),
        sa.Column(
            "blacklisted",
            sa.Boolean(),
            nullable=False,
            comment="Indicates whether the authentication is blacklisted",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fastapi_clean_architecture_ddd_template_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "user_agent",
            "device",
            name="uq_authentications_user_id_user_agent_device",
        ),
    )
    op.create_index(
        "ix_authentications_user_id_user_agent_device",
        "fastapi_clean_architecture_ddd_template_authentications",
        ["user_id", "user_agent", "device"],
        unique=False,
    )
    op.create_table(
        "fastapi_clean_architecture_ddd_template_keys",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable name of the API key",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Optional description of the API key",
        ),
        sa.Column(
            "prefix",
            sa.String(length=32),
            nullable=False,
            comment="Public, non-secret identifier fragment of the key",
        ),
        sa.Column(
            "last_four",
            sa.String(length=4),
            nullable=False,
            comment="Last four characters of the raw key, for masked display",
        ),
        sa.Column(
            "hashed_key",
            sa.String(length=255),
            nullable=False,
            comment="HMAC-SHA256 hash of the raw key; the raw key is never stored",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Expiration timestamp of the key; null means it never expires",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of the last time the key was used to authenticate",
        ),
        sa.Column(
            "created_by",
            sa.UUID(),
            nullable=False,
            comment="Identifier of the user who created the key",
        ),
        sa.Column(
            "updated_by",
            sa.UUID(),
            nullable=False,
            comment="Identifier of the user who last updated the key",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the record",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Indicates whether the record is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["fastapi_clean_architecture_ddd_template_users.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["fastapi_clean_architecture_ddd_template_users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hashed_key", name="uq_keys_hashed_key"),
    )
    op.create_index(
        "ix_keys_created_by",
        "fastapi_clean_architecture_ddd_template_keys",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "ix_keys_prefix",
        "fastapi_clean_architecture_ddd_template_keys",
        ["prefix"],
        unique=False,
    )
    op.create_index(
        "ix_keys_updated_by",
        "fastapi_clean_architecture_ddd_template_keys",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "fastapi_clean_architecture_ddd_template_knowledges",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Unique name of the knowledge record",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Detailed description of the knowledge record",
        ),
        sa.Column(
            "created_by",
            sa.UUID(),
            nullable=False,
            comment="Identifier of the user who created the record",
        ),
        sa.Column(
            "updated_by",
            sa.UUID(),
            nullable=False,
            comment="Identifier of the user who last updated the record",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the record",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Indicates whether the record is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["fastapi_clean_architecture_ddd_template_users.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["fastapi_clean_architecture_ddd_template_users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "ix_knowledges_created_by",
        "fastapi_clean_architecture_ddd_template_knowledges",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "ix_knowledges_name_is_active",
        "fastapi_clean_architecture_ddd_template_knowledges",
        ["name", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_knowledges_updated_by",
        "fastapi_clean_architecture_ddd_template_knowledges",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "fastapi_clean_architecture_ddd_template_notifications",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Identifier of the user who receives this notification",
        ),
        sa.Column(
            "notification_type",
            sa.Enum(
                "KNOWLEDGE_CREATED",
                "KNOWLEDGE_UPDATED",
                "KNOWLEDGE_DELETED",
                "SYSTEM_ALERT",
                name="notification_type_enum",
            ),
            nullable=False,
            comment="Event type that triggered this notification",
        ),
        sa.Column(
            "title",
            sa.String(length=150),
            nullable=False,
            comment="Short title of the notification",
        ),
        sa.Column(
            "body",
            sa.Text(),
            nullable=False,
            comment="Full body text of the notification",
        ),
        sa.Column(
            "redirect_url",
            sa.String(length=2048),
            nullable=True,
            comment="Optional URL for deep linking from the notification",
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Optional JSON payload with internal context data (resource_id, etc.)",
        ),
        sa.Column(
            "originated_from_broadcast",
            sa.String(length=20),
            nullable=True,
            comment="Role targeted by the fan-out broadcast that created this notification, if any",
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether the user has read this notification",
        ),
        sa.Column(
            "read_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the notification was marked as read",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the record",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Indicates whether the record is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["fastapi_clean_architecture_ddd_template_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notifications_user_id_is_active",
        "fastapi_clean_architecture_ddd_template_notifications",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_id_is_read",
        "fastapi_clean_architecture_ddd_template_notifications",
        ["user_id", "is_read"],
        unique=False,
    )
    op.create_table(
        "fastapi_clean_architecture_ddd_template_refresh_tokens",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the refresh token",
        ),
        sa.Column(
            "authentication_id",
            sa.UUID(),
            nullable=False,
            comment="Authentication associated with this refresh token",
        ),
        sa.Column(
            "hashed_jti", sa.Text(), nullable=False, comment="Hashed JTI (JWT ID) value"
        ),
        sa.Column(
            "previous_hashed_jti",
            sa.Text(),
            nullable=True,
            comment="Hashed JTI (JWT ID) value of the previous refresh token",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the refresh token was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Expiration timestamp of the refresh token",
        ),
        sa.Column(
            "revoked",
            sa.Boolean(),
            nullable=False,
            comment="Indicates whether the refresh token was revoked",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the refresh token was revoked",
        ),
        sa.ForeignKeyConstraint(
            ["authentication_id"],
            ["fastapi_clean_architecture_ddd_template_authentications.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "authentication_id", name="uq_refresh_tokens_authentication_id"
        ),
        sa.UniqueConstraint("hashed_jti"),
    )
    op.create_index(
        "ix_refresh_tokens_hashed_jti_revoked",
        "fastapi_clean_architecture_ddd_template_refresh_tokens",
        ["hashed_jti", "revoked"],
        unique=False,
    )
    op.create_table(
        "fastapi_clean_architecture_ddd_template_access_tokens",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the access token",
        ),
        sa.Column(
            "refresh_id",
            sa.UUID(),
            nullable=False,
            comment="Refresh token associated with this access token",
        ),
        sa.Column(
            "hashed_jti", sa.Text(), nullable=False, comment="Hashed JTI (JWT ID) value"
        ),
        sa.Column(
            "previous_hashed_jti",
            sa.Text(),
            nullable=True,
            comment="Hashed JTI (JWT ID) value of the previous access token",
        ),
        sa.Column(
            "permission",
            sa.Enum("ADMIN", "MANAGER", "USER", name="role_enum"),
            nullable=False,
            comment="Permission level associated with the access token",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the access token was created",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Expiration timestamp of the access token",
        ),
        sa.Column(
            "revoked",
            sa.Boolean(),
            nullable=False,
            comment="Indicates whether the refresh token was revoked",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the refresh token was revoked",
        ),
        sa.ForeignKeyConstraint(
            ["refresh_id"],
            ["fastapi_clean_architecture_ddd_template_refresh_tokens.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hashed_jti"),
        sa.UniqueConstraint("previous_hashed_jti"),
        sa.UniqueConstraint("refresh_id", name="uq_access_tokens_refresh_id"),
    )
    op.create_index(
        "ix_access_tokens_hashed_jti_revoked",
        "fastapi_clean_architecture_ddd_template_access_tokens",
        ["hashed_jti", "revoked"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_access_tokens_hashed_jti_revoked",
        table_name="fastapi_clean_architecture_ddd_template_access_tokens",
    )
    op.drop_table("fastapi_clean_architecture_ddd_template_access_tokens")
    op.drop_index(
        "ix_refresh_tokens_hashed_jti_revoked",
        table_name="fastapi_clean_architecture_ddd_template_refresh_tokens",
    )
    op.drop_table("fastapi_clean_architecture_ddd_template_refresh_tokens")
    op.drop_index(
        "ix_notifications_user_id_is_read",
        table_name="fastapi_clean_architecture_ddd_template_notifications",
    )
    op.drop_index(
        "ix_notifications_user_id_is_active",
        table_name="fastapi_clean_architecture_ddd_template_notifications",
    )
    op.drop_table("fastapi_clean_architecture_ddd_template_notifications")
    op.drop_index(
        "ix_knowledges_updated_by",
        table_name="fastapi_clean_architecture_ddd_template_knowledges",
    )
    op.drop_index(
        "ix_knowledges_name_is_active",
        table_name="fastapi_clean_architecture_ddd_template_knowledges",
    )
    op.drop_index(
        "ix_knowledges_created_by",
        table_name="fastapi_clean_architecture_ddd_template_knowledges",
    )
    op.drop_table("fastapi_clean_architecture_ddd_template_knowledges")
    op.drop_index(
        "ix_keys_updated_by", table_name="fastapi_clean_architecture_ddd_template_keys"
    )
    op.drop_index(
        "ix_keys_prefix", table_name="fastapi_clean_architecture_ddd_template_keys"
    )
    op.drop_index(
        "ix_keys_created_by", table_name="fastapi_clean_architecture_ddd_template_keys"
    )
    op.drop_table("fastapi_clean_architecture_ddd_template_keys")
    op.drop_index(
        "ix_authentications_user_id_user_agent_device",
        table_name="fastapi_clean_architecture_ddd_template_authentications",
    )
    op.drop_table("fastapi_clean_architecture_ddd_template_authentications")
    op.drop_index(
        "ix_users_email_is_active",
        table_name="fastapi_clean_architecture_ddd_template_users",
    )
    op.drop_table("fastapi_clean_architecture_ddd_template_users")
    # ### end Alembic commands ###
