"""initial erp schema

Revision ID: 36c2e35e1165
Revises: 
Create Date: 2026-09-29 12:08:31.696706

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36c2e35e1165'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=10000000000, increment=1), nullable=False, comment='Auto-increment 11+ digit identifier'),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=18), nullable=True),
    sa.Column('mobile_number', sa.String(length=18), nullable=True),
    sa.Column('line_id', sa.String(length=100), nullable=True),
    sa.Column('id_card', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NON_BINARY', 'OTHER', name='gender_enum'), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('temporary_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='role_enum'), server_default='USER', nullable=False),
    sa.Column('status', sa.Enum('INACTIVE', 'ACTIVE', 'SUSPENDED', 'DELETED', name='user_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('online_status', sa.Enum('OFFLINE', 'ONLINE', 'AWAY', 'BUSY', name='online_status_enum'), server_default='OFFLINE', nullable=False),
    sa.Column('active_status', sa.SmallInteger(), nullable=True),
    sa.Column('network_id', sa.BigInteger(), nullable=True),
    sa.Column('network_type_id', sa.BigInteger(), nullable=True),
    sa.Column('type_id', sa.BigInteger(), nullable=True),
    sa.Column('system_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verification_code', sa.String(length=64), nullable=True),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_failed_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_notification', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('sms_notification', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('email_notification', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('line_notification', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('public_status', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('information_agreement_status', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email_is_active', 'erp_users', ['email', 'is_active'], unique=False)
    op.create_index('ix_users_status', 'erp_users', ['status'], unique=False)
    op.create_index('ix_users_username', 'erp_users', ['username'], unique=False)
    op.create_table('erp_authentications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the authentication'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Identifier of the user who owns the authentication (BIGINT 11+ digits)'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IP address used when the authentication was created'),
    sa.Column('device', sa.String(length=255), nullable=False, comment='Human readable device name'),
    sa.Column('user_agent', sa.Text(), nullable=False, comment='User agent string of the client'),
    sa.Column('accept_language', sa.String(length=255), nullable=True, comment='Accept-Language header value of the client'),
    sa.Column('accept_encoding', sa.String(length=255), nullable=True, comment='accept_encoding header value of the client'),
    sa.Column('origin', sa.String(length=255), nullable=False, comment='Origin header value of the client'),
    sa.Column('referrer', sa.String(length=255), nullable=True, comment='Referrer header value of the client'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Approximate geographic location of the client'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the authentication was created'),
    sa.Column('last_update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time the authentication was updated'),
    sa.Column('blacklisted', sa.Boolean(), nullable=False, comment='Indicates whether the authentication is blacklisted'),
    sa.ForeignKeyConstraint(['user_id'], ['erp_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'user_agent', 'device', name='uq_authentications_user_id_user_agent_device')
    )
    op.create_index('ix_authentications_user_id_user_agent_device', 'erp_authentications', ['user_id', 'user_agent', 'device'], unique=False)
    op.create_table('erp_keys',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable name of the API key'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the API key'),
    sa.Column('prefix', sa.String(length=32), nullable=False, comment='Public, non-secret identifier fragment of the key'),
    sa.Column('last_four', sa.String(length=4), nullable=False, comment='Last four characters of the raw key, for masked display'),
    sa.Column('hashed_key', sa.String(length=255), nullable=False, comment='HMAC-SHA256 hash of the raw key; the raw key is never stored'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Expiration timestamp of the key; null means it never expires'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last time the key was used to authenticate'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='Identifier of the user (BIGINT) who created the key'),
    sa.Column('updated_by', sa.BigInteger(), nullable=False, comment='Identifier of the user (BIGINT) who last updated the key'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['erp_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['erp_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key', name='uq_keys_hashed_key')
    )
    op.create_index('ix_keys_created_by', 'erp_keys', ['created_by'], unique=False)
    op.create_index('ix_keys_prefix', 'erp_keys', ['prefix'], unique=False)
    op.create_index('ix_keys_updated_by', 'erp_keys', ['updated_by'], unique=False)
    op.create_table('erp_knowledges',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique name of the knowledge record'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the knowledge record'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='Identifier of the user who created the record'),
    sa.Column('updated_by', sa.BigInteger(), nullable=False, comment='Identifier of the user who last updated the record'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['erp_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['erp_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_knowledges_created_by', 'erp_knowledges', ['created_by'], unique=False)
    op.create_index('ix_knowledges_name_is_active', 'erp_knowledges', ['name', 'is_active'], unique=False)
    op.create_index('ix_knowledges_updated_by', 'erp_knowledges', ['updated_by'], unique=False)
    op.create_table('erp_notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Identifier of the user who receives this notification'),
    sa.Column('notification_type', sa.Enum('KNOWLEDGE_CREATED', 'KNOWLEDGE_UPDATED', 'KNOWLEDGE_DELETED', 'SYSTEM_ALERT', name='notification_type_enum'), nullable=False, comment='Event type that triggered this notification'),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Short title of the notification'),
    sa.Column('body', sa.Text(), nullable=False, comment='Full body text of the notification'),
    sa.Column('redirect_url', sa.String(length=2048), nullable=True, comment='Optional URL for deep linking from the notification'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional JSON payload with internal context data (resource_id, etc.)'),
    sa.Column('originated_from_broadcast', sa.String(length=20), nullable=True, comment='Role targeted by the fan-out broadcast that created this notification, if any'),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='Whether the user has read this notification'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the notification was marked as read'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['erp_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_is_active', 'erp_notifications', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_notifications_user_id_is_read', 'erp_notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('erp_refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the refresh token'),
    sa.Column('authentication_id', sa.UUID(), nullable=False, comment='Authentication associated with this refresh token'),
    sa.Column('hashed_jti', sa.Text(), nullable=False, comment='Hashed JTI (JWT ID) value'),
    sa.Column('previous_hashed_jti', sa.Text(), nullable=True, comment='Hashed JTI (JWT ID) value of the previous refresh token'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the refresh token was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp of the refresh token'),
    sa.Column('revoked', sa.Boolean(), nullable=False, comment='Indicates whether the refresh token was revoked'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the refresh token was revoked'),
    sa.ForeignKeyConstraint(['authentication_id'], ['erp_authentications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_id', name='uq_refresh_tokens_authentication_id'),
    sa.UniqueConstraint('hashed_jti')
    )
    op.create_index('ix_refresh_tokens_hashed_jti_revoked', 'erp_refresh_tokens', ['hashed_jti', 'revoked'], unique=False)
    op.create_table('erp_access_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the access token'),
    sa.Column('refresh_id', sa.UUID(), nullable=False, comment='Refresh token associated with this access token'),
    sa.Column('hashed_jti', sa.Text(), nullable=False, comment='Hashed JTI (JWT ID) value'),
    sa.Column('previous_hashed_jti', sa.Text(), nullable=True, comment='Hashed JTI (JWT ID) value of the previous access token'),
    sa.Column('permission', sa.Enum('ADMIN', 'MANAGER', 'USER', name='role_enum'), nullable=False, comment='Permission level associated with the access token'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the access token was created'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp of the access token'),
    sa.Column('revoked', sa.Boolean(), nullable=False, comment='Indicates whether the access token was revoked'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the access token was revoked'),
    sa.ForeignKeyConstraint(['refresh_id'], ['erp_refresh_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_jti'),
    sa.UniqueConstraint('previous_hashed_jti'),
    sa.UniqueConstraint('refresh_id', name='uq_access_tokens_refresh_id')
    )
    op.create_index('ix_access_tokens_hashed_jti_revoked', 'erp_access_tokens', ['hashed_jti', 'revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_tokens_hashed_jti_revoked', table_name='erp_access_tokens')
    op.drop_table('erp_access_tokens')
    op.drop_index('ix_refresh_tokens_hashed_jti_revoked', table_name='erp_refresh_tokens')
    op.drop_table('erp_refresh_tokens')
    op.drop_index('ix_notifications_user_id_is_read', table_name='erp_notifications')
    op.drop_index('ix_notifications_user_id_is_active', table_name='erp_notifications')
    op.drop_table('erp_notifications')
    op.drop_index('ix_knowledges_updated_by', table_name='erp_knowledges')
    op.drop_index('ix_knowledges_name_is_active', table_name='erp_knowledges')
    op.drop_index('ix_knowledges_created_by', table_name='erp_knowledges')
    op.drop_table('erp_knowledges')
    op.drop_index('ix_keys_updated_by', table_name='erp_keys')
    op.drop_index('ix_keys_prefix', table_name='erp_keys')
    op.drop_index('ix_keys_created_by', table_name='erp_keys')
    op.drop_table('erp_keys')
    op.drop_index('ix_authentications_user_id_user_agent_device', table_name='erp_authentications')
    op.drop_table('erp_authentications')
    op.drop_index('ix_users_username', table_name='erp_users')
    op.drop_index('ix_users_status', table_name='erp_users')
    op.drop_index('ix_users_email_is_active', table_name='erp_users')
    op.drop_table('erp_users')
    # ### end Alembic commands ###