"""
Revision Message: add_modules

Revision ID: 4586f82a4d7e
Revises: 04e00cccb1c5
Create Date: 2026-07-21 14:31:38.135137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4586f82a4d7e'
down_revision: Union[str, Sequence[str], None] = '04e00cccb1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('title', sa.String(length=100), nullable=False, comment='Item title'),
    sa.Column('description', sa.String(length=200), nullable=False, comment='Item description'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_batch_job',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Batch job name'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Batch job type'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Job configuration JSON'),
    sa.Column('schedule', sa.String(length=100), nullable=True, comment='Job schedule expression'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='Job status'),
    sa.Column('total_count', sa.Integer(), server_default='0', nullable=False, comment='Total items to process'),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=False, comment='Successfully processed items'),
    sa.Column('fail_count', sa.Integer(), server_default='0', nullable=False, comment='Failed items'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Job start timestamp'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Job finish timestamp'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_batch_job_log',
    sa.Column('job_id', sa.UUID(), nullable=False, comment='Reference to batch job'),
    sa.Column('message', sa.Text(), nullable=False, comment='Log message'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='Log level (info, warning, error)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_car',
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Customer ID'),
    sa.Column('license_plate', sa.String(length=20), nullable=False, comment='License plate'),
    sa.Column('province', sa.String(length=50), nullable=True, comment='Province'),
    sa.Column('brand', sa.String(length=50), nullable=False, comment='Brand'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='Model'),
    sa.Column('sub_model', sa.String(length=100), nullable=True, comment='Sub model'),
    sa.Column('year', sa.Integer(), nullable=True, comment='Year'),
    sa.Column('color', sa.String(length=30), nullable=True, comment='Color'),
    sa.Column('engine_number', sa.String(length=50), nullable=True, comment='Engine number'),
    sa.Column('chassis_number', sa.String(length=50), nullable=True, comment='Chassis number'),
    sa.Column('fuel_type', sa.String(length=20), nullable=True, comment='Fuel type'),
    sa.Column('transmission_type', sa.String(length=20), nullable=True, comment='Transmission type'),
    sa.Column('engine_cc', sa.Integer(), nullable=True, comment='Engine CC'),
    sa.Column('seating_capacity', sa.Integer(), nullable=True, comment='Seating capacity'),
    sa.Column('mileage', sa.Integer(), nullable=False, comment='Mileage'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('whitelabel_id', sa.UUID(), nullable=False, comment='Whitelabel ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('m_customer',
    sa.Column('customer_code', sa.String(length=20), nullable=False, comment='Customer code'),
    sa.Column('full_name', sa.String(length=200), nullable=False, comment='Full name'),
    sa.Column('display_name', sa.String(length=200), nullable=True, comment='Display name'),
    sa.Column('customer_type', sa.String(length=20), nullable=False, comment='Customer type'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status'),
    sa.Column('tax_id', sa.String(length=20), nullable=True, comment='Tax ID'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Phone number'),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True, comment='Secondary phone'),
    sa.Column('address', sa.Text(), nullable=True, comment='Address'),
    sa.Column('province', sa.String(length=100), nullable=True, comment='Province'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('district', sa.String(length=100), nullable=True, comment='District'),
    sa.Column('postal_code', sa.String(length=10), nullable=True, comment='Postal code'),
    sa.Column('country', sa.String(length=50), nullable=False, comment='Country'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='Contact person'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='Contact phone'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.Column('total_visit_count', sa.Integer(), nullable=False, comment='Total visit count'),
    sa.Column('total_spent', sa.Float(), nullable=False, comment='Total spent'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('whitelabel_id', sa.UUID(), nullable=False, comment='Whitelabel ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_table('m_document',
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Stored filename'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original upload filename'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_email_config',
    sa.Column('smtp_host', sa.String(length=200), nullable=False, comment='SMTP server host'),
    sa.Column('smtp_port', sa.Integer(), nullable=False, comment='SMTP server port'),
    sa.Column('smtp_user', sa.String(length=200), nullable=False, comment='SMTP username'),
    sa.Column('from_email', sa.String(length=200), nullable=False, comment='Sender email address'),
    sa.Column('from_name', sa.String(length=200), nullable=False, comment='Sender display name'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether config is active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_email_log',
    sa.Column('to_address', sa.String(length=500), nullable=False, comment='Recipient email address'),
    sa.Column('cc', sa.String(length=500), nullable=True, comment='CC recipients'),
    sa.Column('bcc', sa.String(length=500), nullable=True, comment='BCC recipients'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='Email subject'),
    sa.Column('body', sa.Text(), nullable=False, comment='Email body'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Email status'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='When email was sent'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_payment',
    sa.Column('payment_no', sa.String(length=50), nullable=False, comment='Payment number'),
    sa.Column('invoice_id', sa.UUID(), nullable=True, comment='Invoice ID'),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='Job ID'),
    sa.Column('customer_id', sa.UUID(), nullable=True, comment='Customer ID'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True, comment='Payment date'),
    sa.Column('payment_method_id', sa.UUID(), nullable=True, comment='Payment method ID'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Payment amount'),
    sa.Column('amount_received', sa.Float(), nullable=False, comment='Amount received'),
    sa.Column('change_amount', sa.Float(), nullable=False, comment='Change amount'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency'),
    sa.Column('exchange_rate', sa.Float(), nullable=False, comment='Exchange rate'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Payment status'),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='Reference number'),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='Bank name'),
    sa.Column('cheque_number', sa.String(length=50), nullable=True, comment='Cheque number'),
    sa.Column('cheque_bank', sa.String(length=100), nullable=True, comment='Cheque bank'),
    sa.Column('cheque_date', sa.Date(), nullable=True, comment='Cheque date'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.Column('received_by', sa.UUID(), nullable=True, comment='Received by user ID'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='Approved by user ID'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Approved at'),
    sa.Column('refunded_amount', sa.Float(), nullable=False, comment='Refunded amount'),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True, comment='Refunded at'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_payment_history',
    sa.Column('payment_id', sa.UUID(), nullable=False, comment='Payment ID'),
    sa.Column('from_status', sa.String(length=20), nullable=False, comment='Previous status'),
    sa.Column('to_status', sa.String(length=20), nullable=False, comment='New status'),
    sa.Column('changed_by', sa.UUID(), nullable=True, comment='Changed by user ID'),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True, comment='Changed at'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_purchase_order_detail',
    sa.Column('po_header_id', sa.UUID(), nullable=False, comment='Purchase order header ID'),
    sa.Column('part_id', sa.UUID(), nullable=True, comment='Part ID'),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False, comment='Quantity ordered'),
    sa.Column('quantity_received', sa.Integer(), nullable=False, comment='Quantity received'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='Unit price'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='Total price'),
    sa.Column('discount', sa.Float(), nullable=False, comment='Discount amount'),
    sa.Column('net_price', sa.Float(), nullable=False, comment='Net price after discount'),
    sa.Column('note', sa.Text(), nullable=True, comment='Note'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_purchase_order_header',
    sa.Column('po_no', sa.String(length=50), nullable=False, comment='Purchase order number'),
    sa.Column('quotation_id', sa.UUID(), nullable=True, comment='Related quotation ID'),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='Related job ID'),
    sa.Column('supplier_id', sa.UUID(), nullable=True, comment='Supplier ID'),
    sa.Column('po_date', sa.Date(), nullable=True, comment='Purchase order date'),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True, comment='Expected delivery date'),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True, comment='Actual delivery date'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PO status'),
    sa.Column('subtotal', sa.Float(), nullable=False, comment='Subtotal amount'),
    sa.Column('tax_rate', sa.Float(), nullable=False, comment='Tax rate percentage'),
    sa.Column('tax_amount', sa.Float(), nullable=False, comment='Tax amount'),
    sa.Column('discount_type', sa.String(length=20), nullable=True, comment='Discount type (percentage/fixed)'),
    sa.Column('discount_value', sa.Float(), nullable=False, comment='Discount value'),
    sa.Column('total', sa.Float(), nullable=False, comment='Total amount'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency code'),
    sa.Column('exchange_rate', sa.Float(), nullable=False, comment='Exchange rate'),
    sa.Column('shipping_cost', sa.Float(), nullable=False, comment='Shipping cost'),
    sa.Column('payment_terms', sa.Text(), nullable=True, comment='Payment terms'),
    sa.Column('delivery_address', sa.Text(), nullable=True, comment='Delivery address'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True, comment='Terms and conditions'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='Timestamp when PO was sent'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='Timestamp when PO was confirmed'),
    sa.Column('received_by', sa.UUID(), nullable=True, comment='User who received the goods'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_purchase_order_status_history',
    sa.Column('po_header_id', sa.UUID(), nullable=False, comment='Purchase order header ID'),
    sa.Column('from_status', sa.String(length=20), nullable=False, comment='Previous status'),
    sa.Column('to_status', sa.String(length=20), nullable=False, comment='New status'),
    sa.Column('changed_by', sa.UUID(), nullable=True, comment='User who changed the status'),
    sa.Column('changed_at', sa.DateTime(), nullable=True, comment='Timestamp of status change'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for status change'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_quotation',
    sa.Column('quotation_no', sa.String(length=50), nullable=False, comment='Quotation number'),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='Job ID'),
    sa.Column('customer_id', sa.UUID(), nullable=True, comment='Customer ID'),
    sa.Column('quotation_date', sa.Date(), nullable=True, comment='Quotation date'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='Expiry date'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status'),
    sa.Column('subtotal', sa.Float(), nullable=False, comment='Subtotal'),
    sa.Column('tax_rate', sa.Float(), nullable=False, comment='Tax rate'),
    sa.Column('tax_amount', sa.Float(), nullable=False, comment='Tax amount'),
    sa.Column('discount_type', sa.String(length=20), nullable=True, comment='Discount type'),
    sa.Column('discount_value', sa.Float(), nullable=False, comment='Discount value'),
    sa.Column('total', sa.Float(), nullable=False, comment='Total'),
    sa.Column('amount_in_words_th', sa.Text(), nullable=True, comment='Amount in words (Thai)'),
    sa.Column('amount_in_words_en', sa.Text(), nullable=True, comment='Amount in words (English)'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency'),
    sa.Column('exchange_rate', sa.Float(), nullable=False, comment='Exchange rate'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True, comment='Terms and conditions'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='Approved by user ID'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Approval timestamp'),
    sa.Column('rejected_reason', sa.Text(), nullable=True, comment='Rejection reason'),
    sa.Column('converted_to_po', sa.Boolean(), nullable=False, comment='Converted to PO'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_receipt',
    sa.Column('receipt_no', sa.String(length=50), nullable=False, comment='Receipt number'),
    sa.Column('payment_id', sa.UUID(), nullable=False, comment='Payment ID'),
    sa.Column('invoice_id', sa.UUID(), nullable=True, comment='Invoice ID'),
    sa.Column('customer_id', sa.UUID(), nullable=True, comment='Customer ID'),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=True, comment='Receipt date'),
    sa.Column('receipt_type', sa.String(length=20), nullable=False, comment='Receipt type'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Receipt amount'),
    sa.Column('amount_in_words_th', sa.Text(), nullable=True, comment='Amount in words (Thai)'),
    sa.Column('amount_in_words_en', sa.Text(), nullable=True, comment='Amount in words (English)'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Receipt status'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes'),
    sa.Column('issued_by', sa.UUID(), nullable=True, comment='Issued by user ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_translation',
    sa.Column('locale', sa.String(length=10), nullable=False, comment='Locale code (e.g. en, pt-BR)'),
    sa.Column('key', sa.String(length=255), nullable=False, comment='Translation key'),
    sa.Column('value', sa.Text(), nullable=False, comment='Translated value'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_wos_order',
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='Unique order number'),
    sa.Column('customer_name', sa.String(length=200), nullable=False, comment='Customer full name'),
    sa.Column('customer_email', sa.String(length=200), nullable=False, comment='Customer email address'),
    sa.Column('customer_phone', sa.String(length=50), nullable=True, comment='Customer phone number'),
    sa.Column('items', sa.JSON(), nullable=True, comment='Order items as JSON'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='Total order amount'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='Order status'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier of the record'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_wos_order')
    op.drop_table('m_translation')
    op.drop_table('m_receipt')
    op.drop_table('m_quotation')
    op.drop_table('m_purchase_order_status_history')
    op.drop_table('m_purchase_order_header')
    op.drop_table('m_purchase_order_detail')
    op.drop_table('m_payment_history')
    op.drop_table('m_payment')
    op.drop_table('m_email_log')
    op.drop_table('m_email_config')
    op.drop_table('m_document')
    op.drop_table('m_customer')
    op.drop_table('m_car')
    op.drop_table('m_batch_job_log')
    op.drop_table('m_batch_job')
    op.drop_table('item')
    # ### end Alembic commands ###
