-- ============================================================================
-- FULL SCHEMA: erp_users
-- Compatible with app.modules.user.infrastructure.models.UserModel
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Drop old artifacts
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS erp_users CASCADE;

DROP TYPE IF EXISTS gender_enum         CASCADE;
DROP TYPE IF EXISTS role_enum           CASCADE;
DROP TYPE IF EXISTS user_status_enum    CASCADE;
DROP TYPE IF EXISTS online_status_enum  CASCADE;

-- ---------------------------------------------------------------------------
-- 2. Enum types
-- ---------------------------------------------------------------------------
-- SQLAlchemy's Enum() stores the Python enum *name* by default
CREATE TYPE gender_enum        AS ENUM ('MALE', 'FEMALE', 'NON_BINARY', 'OTHER');
CREATE TYPE role_enum          AS ENUM ('USER', 'ADMIN', 'GUEST');
CREATE TYPE user_status_enum   AS ENUM ('INACTIVE', 'ACTIVE', 'SUSPENDED', 'DELETED');
CREATE TYPE online_status_enum AS ENUM ('OFFLINE', 'ONLINE', 'AWAY', 'BUSY');

-- ---------------------------------------------------------------------------
-- 3. Table
-- ---------------------------------------------------------------------------
CREATE TABLE erp_users (
    -- PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        (START WITH 10000000000 INCREMENT BY 1)
        PRIMARY KEY,

    -- Identity
    first_name     VARCHAR(100),
    last_name      VARCHAR(100),
    preferred_name VARCHAR(100),
    full_name      VARCHAR(200),
    nickname       VARCHAR(100),

    username VARCHAR(150) NOT NULL UNIQUE,
    email    VARCHAR(255) NOT NULL UNIQUE,
    phone         VARCHAR(18),
    mobile_number VARCHAR(18),
    line_id       VARCHAR(100),
    id_card       VARCHAR(20),

    -- Profile
    gender    gender_enum,
    birthdate DATE,
    avatar      TEXT,
    avatar_path TEXT,
    message     TEXT,
    remark      TEXT,

    -- Auth
    hashed_password    VARCHAR(255) NOT NULL,
    temporary_password VARCHAR(255),

    -- Status
    role          role_enum          NOT NULL DEFAULT 'USER',
    status        user_status_enum   NOT NULL DEFAULT 'ACTIVE',
    online_status online_status_enum NOT NULL DEFAULT 'OFFLINE',
    active_status SMALLINT,

    -- Legacy grouping
    network_id      BIGINT DEFAULT 1,
    network_type_id BIGINT DEFAULT 0,
    type_id         BIGINT DEFAULT 0,
    system_id       VARCHAR(50) DEFAULT '1',
    location_id     VARCHAR(50) DEFAULT '1',

    -- Soft delete
    deleted_at DATE,

    -- Security
    is_verified          BOOLEAN NOT NULL DEFAULT FALSE,
    is_superuser         BOOLEAN NOT NULL DEFAULT FALSE,
    verification_code    VARCHAR(64),
    password_reset_token VARCHAR(64),
    password_reset_at    TIMESTAMPTZ,
    login_failed_count   SMALLINT NOT NULL DEFAULT 0,
    last_sign_in_at      TIMESTAMPTZ DEFAULT NOW(),

    -- Preferences
    public_notification           SMALLINT NOT NULL DEFAULT 0,
    sms_notification              SMALLINT NOT NULL DEFAULT 0,
    email_notification            SMALLINT NOT NULL DEFAULT 0,
    line_notification             SMALLINT NOT NULL DEFAULT 0,
    public_status                 SMALLINT NOT NULL DEFAULT 0,
    information_agreement_status  SMALLINT NOT NULL DEFAULT 0,

    -- BaseModel fields (is_active, created_at, updated_at)
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 4. Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX ix_users_email_is_active ON erp_users (email, is_active);
CREATE INDEX ix_users_username       ON erp_users (username);
CREATE INDEX ix_users_status         ON erp_users (status);

COMMIT;