-- ============================================================================
-- ERP-IOT · Full schema for erp_users
-- Matches: app.modules.user.infrastructure.models.UserModel
-- Idempotent: safe to re-run (drops + recreates)
-- ============================================================================

\set ON_ERROR_STOP on

BEGIN;

-- ----------------------------------------------------------------------------
-- 0. OPTIONAL: back up existing table (comment out if you don't want it)
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_name = 'erp_users') THEN
        EXECUTE 'DROP TABLE IF EXISTS erp_users_backup CASCADE';
        EXECUTE 'ALTER TABLE erp_users RENAME TO erp_users_backup';
        RAISE NOTICE 'Existing erp_users renamed to erp_users_backup';
    END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 1. Drop dependent objects (fresh start for the enums)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS erp_users          CASCADE;
DROP TABLE IF EXISTS erp_authentications CASCADE;

DROP TYPE IF EXISTS gender_enum         CASCADE;
DROP TYPE IF EXISTS role_enum           CASCADE;
DROP TYPE IF EXISTS user_status_enum    CASCADE;
DROP TYPE IF EXISTS online_status_enum  CASCADE;

-- ----------------------------------------------------------------------------
-- 2. Enum types
--    SQLAlchemy's Enum(...) stores the Python enum *name* by default, so the
--    labels below are UPPERCASE (e.g. Gender.MALE.name == "MALE").
-- ----------------------------------------------------------------------------
CREATE TYPE gender_enum AS ENUM (
    'MALE',
    'FEMALE',
    'NON_BINARY',
    'OTHER'
);

CREATE TYPE role_enum AS ENUM (
    'ADMIN',
    'USER',
    'GUEST'
);

CREATE TYPE user_status_enum AS ENUM (
    'INACTIVE',
    'ACTIVE',
    'SUSPENDED',
    'DELETED'
);

CREATE TYPE online_status_enum AS ENUM (
    'OFFLINE',
    'ONLINE',
    'AWAY',
    'BUSY'
);

-- ----------------------------------------------------------------------------
-- 3. erp_users
-- ----------------------------------------------------------------------------
CREATE TABLE erp_users (
    -- ── Primary key: BIGINT auto-increment starting at 10 000 000 000 ──────
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 10000000000 INCREMENT BY 1)
        PRIMARY KEY,

    -- ── Identity ───────────────────────────────────────────────────────────
    first_name     VARCHAR(100),
    last_name      VARCHAR(100),
    preferred_name VARCHAR(100),
    full_name      VARCHAR(200),
    nickname       VARCHAR(100),

    username VARCHAR(150) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    phone         VARCHAR(18),
    mobile_number VARCHAR(18),
    line_id       VARCHAR(100),
    id_card       VARCHAR(20),

    -- ── Profile ────────────────────────────────────────────────────────────
    gender      gender_enum,
    birthdate   DATE,
    avatar      TEXT,
    avatar_path TEXT,
    message     TEXT,
    remark      TEXT,

    -- ── Auth ───────────────────────────────────────────────────────────────
    hashed_password    VARCHAR(255) NOT NULL,
    temporary_password VARCHAR(255),

    -- ── Status ─────────────────────────────────────────────────────────────
    role          role_enum          NOT NULL DEFAULT 'USER',
    status        user_status_enum   NOT NULL DEFAULT 'ACTIVE',
    online_status online_status_enum NOT NULL DEFAULT 'OFFLINE',
    active_status SMALLINT,

    -- ── Legacy grouping ────────────────────────────────────────────────────
    network_id      BIGINT      DEFAULT 1,
    network_type_id BIGINT      DEFAULT 0,
    type_id         BIGINT      DEFAULT 0,
    system_id       VARCHAR(50) DEFAULT '1',
    location_id     VARCHAR(50) DEFAULT '1',

    -- ── Soft delete ────────────────────────────────────────────────────────
    deleted_at DATE,

    -- ── Security ───────────────────────────────────────────────────────────
    is_verified          BOOLEAN     NOT NULL DEFAULT FALSE,
    is_superuser         BOOLEAN     NOT NULL DEFAULT FALSE,
    verification_code    VARCHAR(64),
    password_reset_token VARCHAR(64),
    password_reset_at    TIMESTAMPTZ,
    login_failed_count   SMALLINT    NOT NULL DEFAULT 0,
    last_sign_in_at      TIMESTAMPTZ DEFAULT NOW(),

    -- ── Preferences (stored as int2 to match SQLAlchemy SmallInteger) ──────
    public_notification          SMALLINT NOT NULL DEFAULT 0,
    sms_notification             SMALLINT NOT NULL DEFAULT 0,
    email_notification           SMALLINT NOT NULL DEFAULT 0,
    line_notification            SMALLINT NOT NULL DEFAULT 0,
    public_status                SMALLINT NOT NULL DEFAULT 0,
    information_agreement_status SMALLINT NOT NULL DEFAULT 0,

    -- ── BaseModel fields ───────────────────────────────────────────────────
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 4. Constraints & indexes
-- ----------------------------------------------------------------------------
ALTER TABLE erp_users
    ADD CONSTRAINT uq_users_username UNIQUE (username),
    ADD CONSTRAINT uq_users_email    UNIQUE (email);

CREATE INDEX ix_users_email_is_active ON erp_users (email, is_active);
CREATE INDEX ix_users_username        ON erp_users (username);
CREATE INDEX ix_users_status          ON erp_users (status);

-- ----------------------------------------------------------------------------
-- 5. updated_at auto-touch trigger
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_erp_users_updated_at ON erp_users;
CREATE TRIGGER trg_erp_users_updated_at
    BEFORE UPDATE ON erp_users
    FOR EACH ROW
    EXECUTE FUNCTION trg_set_updated_at();

-- ----------------------------------------------------------------------------
-- 6. (Optional) erp_authentications — required by the UserModel relationship.
--    Uncomment and adapt column names if your AuthenticationModel differs.
-- ----------------------------------------------------------------------------
-- CREATE TABLE erp_authentications (
--     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     user_id    BIGINT NOT NULL REFERENCES erp_users(id) ON DELETE CASCADE,
--     token      VARCHAR(512) NOT NULL,
--     expires_at TIMESTAMPTZ,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
-- CREATE INDEX ix_auth_user_id ON erp_authentications (user_id);

COMMIT;

-- ============================================================================
-- 7. Verification
-- ============================================================================
\echo '--- erp_users columns ---'
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'erp_users'
ORDER BY ordinal_position;

\echo '--- enum types ---'
SELECT t.typname AS enum_type,
       string_agg(e.enumlabel, ', ' ORDER BY e.enumsortorder) AS labels
FROM pg_type t
JOIN pg_enum e ON t.oid = e.enumtypid
WHERE t.typname IN ('gender_enum','role_enum','user_status_enum','online_status_enum')
GROUP BY t.typname
ORDER BY t.typname;

\echo '--- indexes ---'
SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'erp_users';

-- ============================================================================
-- 8. Rollback (run manually if needed)
-- ============================================================================
-- BEGIN;
--   DROP TABLE IF EXISTS erp_users CASCADE;
--   DROP TYPE  IF EXISTS gender_enum        CASCADE;
--   DROP TYPE  IF EXISTS role_enum          CASCADE;
--   DROP TYPE  IF EXISTS user_status_enum   CASCADE;
--   DROP TYPE  IF EXISTS online_status_enum CASCADE;
--   -- restore backup:
--   -- ALTER TABLE erp_users_backup RENAME TO erp_users;
-- COMMIT;